### ISSUE TITLE
Documentation on SUSHI Configuration not quite right for dependencies

### ISSUE THREAD

**Issue by cmoesel** [FSHSchool/site#21]
The current doc contains this example of a complex dependency:
```
dependencies:
  hl7.fhir.us.mcode:
    uri: http://hl7.org/fhir/us/mcode
    version: 1.0.0
```
There are two ways this should be improved:
* The `id` parameter should be included
* The URL should be the URL for the IG resource

So... this example should be updated to:
```
dependencies:
  hl7.fhir.us.mcode:
    id: mcode
    uri: http://hl7.org/fhir/us/mcode/ImplementationGuide/hl7.fhir.us.mcode
    version: 1.0.0
```
